### PR TITLE
fix: dark & light mode for the icon

### PR DESCRIPTION
**Pull request by gsimone**
CodeSandbox logo&nbsp; Open in CodeSandbox <a href="https://codesandbox.io/p/github/codesandbox/open-in-codesandbox/draft/elegant-wind">Web Editor</a> | <a href="https://codesandbox.io/p/vscode?owner=codesandbox&repo=open-in-codesandbox&branch=draft/elegant-wind">VS Code</a>

### CODE REVIEW

**Comment by gsimone** [comment]
@aj-foster could we have the action here so we see it running on itself? 🤝

**Comment by aj-foster** [comment]
@gsimone Is the icon not working presently? The SVG has embedded styles that should switch light/dark automatically, but I haven't tested in many browsers.

**Comment by gsimone** [comment]
Doesn't work if you have light/dark mode enabled only on GitHub since the media query uses the system-wide setting 🥇

**Comment by aj-foster** [comment]
Got it. Should we remove the style from the other file, then? In case someone chooses light mode but the system setting is dark.

**Review by aj-foster — APPROVED** [review]

**Pull request merged**
